global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'golang'
    static_configs:
      - targets: [ 'docker.for.mac.localhost:3001' ]

  - job_name: 'system'
    static_configs:
      - targets: [ 'docker.for.mac.localhost:9100' ]
#      - targets: ['localhost:9100']
